apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: nuxt
  replicas: 3
  template:
    metadata:
      labels:
        app: nuxt
    spec:
      containers:
      - name: nuxt-app
        image: index.docker.io/nishi7409/1sre
        imagePullPolicy: Always
        ports:
          - containerPort: 3000