# Generated by Django 4.2 on 2023-04-08 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('used', models.BooleanField(default=False)),
                ('userID', models.UUIDField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(max_length=255)),
                ('lastName', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('premium', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
