on:
  schedule:
    - cron: '0 0 * * 0'
permissions:
  actions: write
  contents: write
  
jobs:
  conversion:
    name: Grab JSON file from the Manual repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      

      - name: Commit files
        run: |
          git config user.email "automation@github.com"
          git config user.name "automation"
          git add -A
          git commit -am 'json update'
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main, dev
          force: true